spring:
  application:
    name: finance-api
  data:
    mongodb:
      database: ${spring.application.name}
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.dkvbydh.mongodb.net/${spring.application.name}?retryWrites=true&w=majority
