spring:
  application:
    name: finance-api
  data:
    mongodb:
      database: ${spring.application.name}
      uri: mongodb+srv://${mongodb-user}:${mongodb-password}@cluster0.dkvbydh.mongodb.net/${spring.application.name}?retryWrites=true&w=majority
